Public Class Cliente
    Public Property CodCliente As Integer
    Public Property NomeCliente As String
    Public Property TipoCliente As String
    Public Property CPF As String
    Public Property CGC As String
    Public Property IE As String
    Public Property Fantasia As String
    Public Property Nacionalidade As String
    Public Property EstadoCivil As String
    Public Property Profissao As String
    Public Property Contato As String
    Public Property fone1 As String
    Public Property FoneCobranca As String
    Public Property Fone2 As String
    Public Property Fax As String
    Public Property Rua As String
    Public Property Numero As String
    Public Property Complemento As String
    Public Property Bairro As String
    Public Property Cidade As String
    Public Property CodCidade As String
    Public Property UF As String
    Public Property CEP As String
    Public Property OBS As String
    Public Property Email As String
    Public Property Perfil As String
    Public Property Rota As Integer
    Public Property DataNasc As Date
    Public Property RG As String
    Public Property Pai As String
    Public Property Mae As String
    Public Property RuaC As String
    Public Property ComplementoC As String
    Public Property BairroC As String
    Public Property CidadeC As String
    Public Property UfC As String
    Public Property CepC As String
    Public Property RuaE As String
    Public Property NumeroE As String
    Public Property BairroE As String
    Public Property CidadeE As String
    Public Property UFE As String
    Public Property CEPE As String
    Public Property SPC As String
    Public Property Renda As Single
    Public Property RendaFamiliar As Single
    Public Property LimiteCredito As Single
    Public Property LocalTrabalho As String
    Public Property Admissao As Date
    Public Property ATIVO As Boolean
    Public Property GrupoFoco As Boolean
    Public Property EndTrab As String
    Public Property FoneTrab As String
    Public Property CreditoUtilizado As Single
    Public Property Vendedor As String
    Public Property NVender As Boolean
    Public Property NLocar As Boolean
    Public Property FoneContato As String
    Public Property Representante As String
    Public Property TipoContato As String
    Public Property Email1 As String
    Public Property Excluido As Boolean
    Public Property Maquina As String
    Public Property Usuario As String
    Public Property Ponteiro As Long
    Public Property DataCadastro As String
End Class


